# Generated by Django 3.2.18 on 2023-03-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-public_day']},
        ),
    ]
